### ISSUE TITLE
pdfgui "no module named 'wx' error" for pip installed diffpy.pdfgui==3.1.0rc4 (Apple M1)

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.pdfgui#200]
As instructed by @sbillinge, I tried the following steps:

```
> conda deactivate
> mamba create -n pdfgui-test311 python=3.11 
> conda activate pdfgui-test311
> pip install diffpy.pdfgui==3.1.0rc4
> pdfgui
```

Pip installation works. But, I get the following error when I type `pdfgui`

```
imac@imacs-iMac ~ % pdfgui                                   
Traceback (most recent call last):
  File "/Users/imac/miniconda3/envs/pdfgui-test312/bin/pdfgui", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/imac/miniconda3/envs/pdfgui-test312/lib/python3.12/site-packages/diffpy/pdfgui/applications/pdfgui.py", line 118, in main
    import diffpy.pdfgui.gui.main as guimain
  File "/Users/imac/miniconda3/envs/pdfgui-test312/lib/python3.12/site-packages/diffpy/pdfgui/gui/main.py", line 19, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
````

I checked that the regular installation procedure worked:

```
CONDA_SUBDIR=osx-64 conda create -n pdfgui39 python=3.9
conda activate  pdfgui39
conda config --env --set subdir osx-64
conda install -c conda-forge diffpy.pdfgui
pdfgui
```

**Comment by Tieqiong** [comment]
@bobleesj Thanks. When you pip install the package you would also like to install all the requirements. This is not necessary when installing from Conda-forge because it will automatically install everything for you. In this case `wx` means the `wxpython` package which is one of the requirements.
A good way to install requirements easily is to cd to the package dir then run Conda install --file requirements/run.txt (depend on what you want to do you might also want to install test.txt or build.txt).
I guess you want to test running pdfgui with the latest pdffit2==1.4.4rc1. So after installing all of the requirements you then (or before installing requirements) uninstall the original pdffit2 you get from Conda-forge and then do the pip install. After this run Conda list to check if everything is correct.

**Comment by Tieqiong** [comment]
@bobleesj This is very strange, as on my Mac it install `fonttools == 4.53.1` for me. Maybe try uninstall it and then install?

**Comment by bobleesj** [comment]
@bobleesj check this again after recookicuttered

**Comment by bobleesj** [comment]
@sbillinge Please include this to the 3.1.0 milestone list!

**Comment by bobleesj** [comment]
Closing - `wx` is automatically installed during `pip install` since `wxpython` is in th `run.txt` file.
